#!/bin/bash
#
# Author : Jonathan Sanfilippo
# Date: Jun 2023
# Version 1.0.0: archiso configurazione e script

bk=$(gsettings set org.gnome.desktop.background  picture-uri /usr/share/backgrounds/core/blossom-floral-bouquet.jpg)
bk2=$(gsettings set org.gnome.desktop.background  picture-uri-dark /usr/share/backgrounds/core/blossom-floral-bouquet.jpg)
ex1=$(gnome-extensions enable  user-theme@gnome-shell-extensions.gcampax.github.com)
ex2=$(gnome-extensions enable ding@rastersoft.com)
ex3=$(gnome-extensions enable appindicatorsupport@rgcjonas.gmail.com)
ex4=$(gnome-extensions enable arch-update@RaphaelRochet)
ex5=$(gnome-extensions enable lockkeys@vaina.lt)
ex6=$(gnome-extensions enable nightthemeswitcher@romainvigier.fr)

shell=$(gsettings set org.gnome.shell.extensions.user-theme name "Core")
legacx=$(gsettings set org.gnome.desktop.interface gtk-theme "Core")
icn=$(gsettings set org.gnome.desktop.interface icon-theme 'Core')
cur=$(gsettings set org.gnome.desktop.interface cursor-theme 'Core')
nauicn=$(gsettings set org.gnome.nautilus.icon-view default-zoom-level small-plus)
fnts=$(gsettings set org.gnome.desktop.interface font-name 'Architalia Regular 12')
fnts2=$(gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Architalia Bold 12')
fnts3=$(gsettings set org.gnome.desktop.interface monospace-font-name 'Architalia Mono Bold 11')
but=$(gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close")
vol=$(gsettings set org.gnome.desktop.sound allow-volume-above-100-percent true)

terminal="core-terminal-nord-theme"


start(){   
   $ex1
   $ex2
   $ex3
   $ex4
   $ex5
   $ex6

   $shell
   $legacx
   $bk
   $bk2
   $icn
   $cur
   $nauicn
   $fnts
   $fnts2
   $fnts3
   $but
   $vol
   
   $terminal
   
   rm -rf $HOME/.config/autostart/startx.desktop
}

start
