#!/bin/bash
#
# Author : Jonathan Sanfilippo
# Date: Jun 2023
# Version 1.0.0: archiso configurazione e script

bk=$(gsettings set org.gnome.desktop.background  picture-uri /usr/share/backgrounds/core/himalaya-day.png)
bk2=$(gsettings set org.gnome.desktop.background  picture-uri-dark /usr/share/backgrounds/core/himalaya-night.png)
ex1=$(gnome-extensions enable  user-theme@gnome-shell-extensions.gcampax.github.com)
ex2=$(gnome-extensions enable ding@rastersoft.com)
ex3=$(gnome-extensions enable appindicatorsupport@rgcjonas.gmail.com)
ex4=$(gnome-extensions enable arch-update@RaphaelRochet)
ex5=$(gnome-extensions enable lockkeys@vaina.lt)
ex6=$(gnome-extensions enable nightthemeswitcher@romainvigier.fr)
ex7=$(gnome-extensions enable dash-to-dock@micxgx.gmail.com)
ex8=$(gnome-extensions enable RecentItems@bananenfisch.net)
ex9=$(gnome-extensions enable username_in_shell_panel@raviprak)
ex10=$(gnome-extensions enable notifications-alert-on-user-menu@hackedbellini.gmail.com)
ex11=$(gnome-extensions enable mediacontrols@cliffniff.github.com)
ex12=$(gnome-extensions enable openweather-extension@jenslody.de)

shell=$(gsettings set org.gnome.shell.extensions.user-theme name "Core")
legacx=$(gsettings set org.gnome.desktop.interface gtk-theme "Core")
icn=$(gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark')
#cur=$(gsettings set org.gnome.desktop.interface cursor-theme 'Core')
nauicn=$(gsettings set org.gnome.nautilus.icon-view default-zoom-level small-plus)
fnts=$(gsettings set org.gnome.desktop.interface font-name 'Architalia Regular 12')
fnts2=$(gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Architalia Bold 12')
fnts3=$(gsettings set org.gnome.desktop.interface monospace-font-name 'Architalia Mono Bold 11')
but=$(gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close")
vol=$(gsettings set org.gnome.desktop.sound allow-volume-above-100-percent true)
copykb=$(cp -rp /etc/vconsole.conf $HOME/.cache/vconsole.conf)
kb=$(sed -n 's/KEYMAP=//p' $HOME/.cache/vconsole.conf)
kl=$(gsettings set org.gnome.desktop.input-sources sources "[('xkb', '$kb')]")


terminal="core-terminal-nord-theme"


start(){   
   $ex1
   $ex2
   $ex3
   $ex4
   $ex5
   $ex6
   $ex7
   $ex8
   $ex9
   $ex10
   $ex11
   $ex12
   
   $shell
   $legacx
   $bk
   $bk2
   $icn
   #$cur
   $nauicn
   $fnts
   $fnts2
   $fnts3
   $but
   $vol
   
   $terminal
   $copykb
   $kl
   
   rm -rf $HOME/.config/autostart/{startx.desktop,welcome.desktop}
}

start
